menu_itemのモデルとテーブルができました
VantanProject/wakashachi_back pull request #7
Opened 2024-12-05 11:30 UTC by tomoto-png

menu_itemができました

2024-12-05 11:35 UTC, katedegree requested changes
$table->unsignedInteger()を使用してください

2024-12-07 02:35 UTC, Kate0418 requested changes

2024-12-07 02:35 UTC, Kate0418 commented on laravel-app/app/Models/MenuItem.php
> +}
widthです。

2024-12-09 00:05 UTC, Kate0418 approved these changes
All OK

2024-12-09 05:28 UTC, merged