Merchモデルの作成
VantanProject/wakashachi_back pull request #8
Opened 2024-12-05 11:31 UTC by kaito0523

img_url,price,company_idカラムのテーブルです

2024-12-05 11:40 UTC, Kate0418 requested changes

2024-12-05 11:40 UTC, Kate0418 commented on laravel-app/database/migrations/2024_12_05_112626_create_merches_table.php
> +            $table->unsignedBigInteger('company_id');
> $table->string('img_url');

textに

> $table->integer('price');

unsignedIntegerに

2024-12-07 02:46 UTC, Kate0418 requested changes

2024-12-07 02:46 UTC, Kate0418 commented on laravel-app/database/migrations/2024_12_05_112626_create_merches_table.php
> +        });
- すまんん、これにしてもろて
```suggestion
        Schema::create('merches', function (Blueprint $table) {
            $table->id();
            $table->string('img_url');
            $table->unsignedInteger('price');
            $table->unsignedBigInteger('company_id');
            $table->timestamps();
        });
```

2024-12-07 17:18 UTC, Kate0418 approved these changes
なんちゅう時間に。。

2024-12-07 17:36 UTC, kaito0523 commented on laravel-app/database/migrations/2024_12_05_112626_create_merches_table.php
> +        });
俺が読み違えてたすみません

2024-12-07 17:41 UTC, kaito0523 commented
出かけてたのです。。。すまないです

2024-12-07 17:41 UTC, merged